inherit_from: .rubocop_todo.yml


AllCops:
  DisabledByDefault: false
  TargetRubyVersion: 2.7.2
  Exclude:
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*.rb'
    - 'bin/bundle'
    # only until data is migrated
    - 'scripts/**/*.rb'